apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search-proc.my-apps.tap.20240110153648.0.0+build.02e9424
spec:
  refName: where-for-dinner-search-proc.my-apps.tap
  version: 20240110153648.0.0+build.02e9424
  releaseNotes: |
    Release v20240110153648.0.0+build.02e9424 of package where-for-dinner-search-proc.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-10-01-2024-09-40-26-040797392/where-for-dinner-search-proc-my-apps-bundle@sha256:a1ebdbad06a756f2034fa50b24091954e48fd0515830c9303af93cb2145b2a3d
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

